SELECT C.NOME_COMPLETO,
COUNT(*) AS TOTAL_AVALIACOES 
FROM TB_CLIENTE C
JOIN TB_AVALIACAO A
ON C.ID_CLIENTE = A.ID_CLIENTE
WHERE C.ID_CLIENTE = 1
GROUP BY C.ID_CLIENTE, C.NOME_COMPLETO
ORDER BY TOTAL_AVALIACOES DESC;
