SELECT C.NOME_COMPLETO AS Cliente, P.NOME AS Produto, A.NOTA, A.COMENTARIO, A.DATA
FROM TB_AVALIACAO A
JOIN TB_CLIENTE C ON A.ID_CLIENTE = C.ID_CLIENTE
JOIN TB_PRODUTO P ON A.ID_PRODUTO = P.ID_PRODUTO
WHERE P.ID_PRODUTO = 3
ORDER BY A.DATA DESC