SELECT P.ID_PEDIDO, C.NOME_COMPLETO, P.VALOR_TOTAL, PG.TIPO, PG.STATUS
FROM TB_PEDIDO P
JOIN TB_CLIENTE C
ON P.ID_CLIENTE = C.ID_CLIENTE
JOIN TB_PAGAMENTO PG
ON P.ID_PEDIDO = PG.ID_PEDIDO
WHERE C.ID_CLIENTE = 1
ORDER BY P.ID_PEDIDO;