SELECT C.NOME_COMPLETO AS Cliente, P.ID_PEDIDO, P.VALOR_TOTAL,
P.STATUS AS Status_Pedido,
PG.TIPO AS Forma_Pagamento,
PG.STATUS AS Status_Pagamento,
E.STATUS AS Status_Entrega,
E.DATA AS Data_Entrega
FROM TB_CLIENTE C
JOIN TB_PEDIDO P
ON C.ID_CLIENTE = P.ID_CLIENTE
JOIN TB_PAGAMENTO PG
ON P.ID_PEDIDO = PG.ID_PEDIDO
JOIN TB_ENTREGA E
ON P.ID_PEDIDO = E.ID_PEDIDO
WHERE C.ID_CLIENTE = 1
ORDER BY P.ID_PEDIDO;