SELECT P.ID_PEDIDO, C.NOME_COMPLETO, E.DATA, E.STATUS
FROM TB_PEDIDO P
JOIN TB_CLIENTE C
ON C.ID_CLIENTE = P.ID_CLIENTE
JOIN TB_ENTREGA E
ON E.ID_PEDIDO = P.ID_PEDIDO
WHERE C.ID_CLIENTE = 1
ORDER BY E.DATA;