SELECT C.ID_CARRINHO, CLI.NOME_COMPLETO, P.NOME AS PRODUTO, IC.QUANTIDADE, IC.VALOR_UNITARIO
FROM TB_ITEM_CARRINHO IC
JOIN TB_CARRINHO C ON IC.ID_CARRINHO = C.ID_CARRINHO
JOIN TB_CLIENTE CLI ON C.ID_CLIENTE = CLI.ID_CLIENTE
JOIN TB_PRODUTO P ON IC.ID_PRODUTO = P.ID_PRODUTO
WHERE CLI.ID_CLIENTE = 1
ORDER BY C.ID_CARRINHO;