SELECT P.NOME AS PRODUTO, C.NOME AS CATEGORIA 
FROM TB_PRODUTO P 
JOIN TB_PRODUTO_CATEGORIA PC 
ON P.ID_PRODUTO = PC.ID_PRODUTO 
JOIN TB_CATEGORIA C 
ON PC.ID_CATEGORIA = C.ID_CATEGORIA 
ORDER BY C.NOME;