SELECT P.ID_PRODUTO, P.NOME AS PRODUTO, M.NOME AS MARCA, P.PRECO, P.TAMANHO, P.DESCRICAO, round(AVG(A.NOTA), 1) AS AVALIACAO
FROM TB_PRODUTO P 
JOIN TB_MARCA M ON P.ID_MARCA = M.ID_MARCA
LEFT JOIN tb_avaliacao A ON P.ID_PRODUTO = A.ID_PRODUTO
WHERE P.ID_PRODUTO = 7