SELECT C.ID_CARRINHO, CLI.NOME_COMPLETO, SUM(IC.QUANTIDADE * IC.VALOR_UNITARIO) AS TOTAL_CARRINHO
FROM TB_CARRINHO C
JOIN TB_CLIENTE CLI
ON CLI.ID_CLIENTE = C.ID_CLIENTE
JOIN TB_ITEM_CARRINHO IC
ON IC.ID_CARRINHO = C.ID_CARRINHO
WHERE CLI.ID_CLIENTE = 1
GROUP BY C.ID_CARRINHO, CLI.NOME_COMPLETO
ORDER BY TOTAL_CARRINHO DESC;